#spring.jpa.hibernate.ddl-auto=update
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:file:C:/Users/mycat/Desktop/Server Side/neiu-cs-321/the-astrology-app/dbdata
#spring.datasource.username=admin
#spring.datasource.password=
#spring.datasource.driver-class-name=org.h2.Driver

---
spring:
  jpa:
    hibernate:
      ddl-auto: update #create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${CLEARDB_DATABASE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    initialization-mode: always
    platform: mysql

server:
  port: ${PORT}
  error:
    whitelabel:
      enabled: false
    path: /error

astrology:
  birthday:
    pageSize: 10
